name: Generate Reuters Health RSS

on:
  schedule:
    - cron: "0 * * * *"    # chaque heure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen

      - name: Run Reuters RSS script
        run: python reuters_health_rss.py

      - name: Commit & push RSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/reuters_healthcare_pharma.xml
          git commit -m "chore: update Reuters Health RSS" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
